version: '3.8'

services:
  
  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    
    restart: always
    
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - pg-data:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    
    restart: always
    
    ports:
      - 5050:80
    
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin

    volumes:
      - pgadmin-data:/var/lib/pgadmin
  
volumes:
  pg-data:
  pgadmin-data:
